# wrangler.toml ‑‑ checked‐in at repo root
name              = "reposnap-web-demo"     # any slug
compatibility_date= "2025-04-20"

[site]            # serves the static build
bucket = "./dist"

# optional niceties
# account_id       = "xxxx"
# workers_dev      = false        # if you only want custom domains
# compatibility_flags = ["nodejs_compat"]
