name: "Upload to Cloudflare R2"
description: "Uploads build artifacts to Cloudflare R2"

inputs:
  source-dir:
    description: "Directory containing the artifacts to upload"
    required: true
  version:
    description: "Version string to append to the destination directory (e.g., v1.0.0)"
    required: true
  r2-account-id:
    description: "Cloudflare R2 Account ID"
    required: true
  r2-access-key-id:
    description: "Cloudflare R2 Access Key ID"
    required: true
  r2-secret-access-key:
    description: "Cloudflare R2 Secret Access Key"
    required: true
  r2-bucket:
    description: "Cloudflare R2 Bucket Name"
    required: true

outputs:
  result:
    description: "Result of the upload (success or failure)"
    value: ${{ steps.upload.outputs.result }}
  file-urls:
    description: "URLs of the uploaded files"
    value: ${{ steps.upload.outputs.file-urls }}

runs:
  using: "composite"
  steps:
    - name: Upload to R2
      id: upload
      uses: ryand56/r2-upload-action@latest
      with:
        r2-account-id: ${{ inputs.r2-account-id }}
        r2-access-key-id: ${{ inputs.r2-access-key-id }}
        r2-secret-access-key: ${{ inputs.r2-secret-access-key }}
        r2-bucket: ${{ inputs.r2-bucket }}
        source-dir: ${{ inputs.source-dir }}
        destination-dir: releases/${{ inputs.version }}
        output-file-url: true