name: "Get Tauri Release Version"
description: "Extracts the version from tauri.conf.json and sets it as an output"

outputs:
  version:
    description: "The extracted version from tauri.conf.json"
    value: ${{ steps.get-package-version-unix.outputs.version || steps.get-package-version-windows.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Get Package Version (Unix)
      if: runner.os != 'Windows'
      id: get-package-version-unix
      run: |
        VERSION=$(jq -r '.version' src-tauri/tauri.conf.json)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get Package Version (Windows)
      if: runner.os == 'Windows'
      id: get-package-version-windows
      run: |
        $version = (Get-Content src-tauri/tauri.conf.json | ConvertFrom-Json).version
        "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      shell: powershell
