name: Build Tauri App (macOS)

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: "Deploy to R2"
        required: false
        type: boolean
        default: false

jobs:
  build-macos:
    permissions:
      contents: write
    strategy:
      matrix:
        target: ["aarch64-apple-darwin", "x86_64-apple-darwin"]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install frontend dependencies
        run: bun install

      - name: Build and publish Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        with:
          tagName: v__VERSION__
          releaseName: "RepoSnap v__VERSION__ (macOS ${{ matrix.target }})"
          releaseBody: "macOS build for ${{ matrix.target }} (.dmg)."
          releaseDraft: true
          args: "--target ${{ matrix.target }} --bundles app,dmg --verbose"

      - name: Get Package Version
        uses: ./.github/actions/get-version-from-package
        id: package-version

      - name: Check Artifacts
        run: |
          echo "macOS directory contents:"
          ls -la src-tauri/target/${{ matrix.target }}/release/bundle/macos/
          echo "DMG directory contents:"
          ls -la src-tauri/target/${{ matrix.target }}/release/bundle/dmg/

      - name: Upload to R2 (Updater Artifacts)
        if: ${{ github.event.inputs.deploy == 'true' }}
        uses: ryand56/r2-upload-action@latest
        id: r2-upload-updater
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: src-tauri/target/${{ matrix.target }}/release/bundle/macos
          destination-dir: releases/${{ steps.package-version.outputs.version }}
          output-file-url: true

      - name: Upload to R2 (DMG)
        if: ${{ github.event.inputs.deploy == 'true' }}
        uses: ryand56/r2-upload-action@latest
        id: r2-upload-dmg
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: src-tauri/target/${{ matrix.target }}/release/bundle/dmg
          destination-dir: releases/${{ steps.package-version.outputs.version }}
          output-file-url: true

      - name: Debug R2 Upload Outputs
        if: ${{ github.event.inputs.deploy == 'true' }}
        run: |
          echo "DMG Upload Result: ${{ steps.r2-upload-dmg.outputs.result }}"
          echo "DMG Uploaded File URLs: ${{ steps.r2-upload-dmg.outputs.file-urls }}"
          echo "Updater Upload Result: ${{ steps.r2-upload-updater.outputs.result }}"
          echo "Updater Uploaded File URLs: ${{ steps.r2-upload-updater.outputs.file-urls }}"
