name: Build Tauri App (All Platforms)

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: "Deploy to R2"
        required: false
        type: boolean
        default: false

jobs:
  build-and-release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            target: aarch64-apple-darwin
            args: "--target aarch64-apple-darwin --bundles dmg"
            r2-source: src-tauri/target/aarch64-apple-darwin/release/bundle/dmg
          - platform: macos-latest
            target: x86_64-apple-darwin
            args: "--target x86_64-apple-darwin --bundles dmg"
            r2-source: src-tauri/target/x86_64-apple-darwin/release/bundle/dmg
          - platform: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            args: "--bundles appimage"
            r2-source: src-tauri/target/release/bundle/appimage
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
            args: "--bundles msi"
            r2-source: src-tauri/target/release/bundle/msi

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && format('{0},{1}', matrix.target, 'aarch64-apple-darwin,x86_64-apple-darwin') || matrix.target }}

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: bun install

      - uses: tauri-apps/tauri-action@v0
        id: tauri-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        with:
          tagName: v__VERSION__
          releaseName: "RepoSnap v__VERSION__"
          releaseBody: "Draft release for v__VERSION__."
          releaseDraft: true
          args: ${{ matrix.args }} --verbose

      - name: Get Package Version
        uses: ./.github/actions/get-version-from-package
        id: package-version

      - name: Upload to R2
        if: ${{ github.event.inputs.deploy == 'true' }}
        uses: ./.github/actions/upload-to-r2
        id: r2-upload
        with:
          source-dir: ${{ matrix.r2-source }}
          version: ${{ steps.package-version.outputs.version }}

      - name: Debug R2 Upload Outputs
        if: ${{ github.event.inputs.deploy == 'true' }}
        run: |
          echo "Upload Result: ${{ steps.r2-upload.outputs.result }}"
          echo "Uploaded File URLs: ${{ steps.r2-upload.outputs.file-urls }}"
