name: Build Tauri App (Linux)

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: "Deploy to R2"
        required: false
        type: boolean
        default: false

jobs:
  build-linux:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: bun install

      - name: Build and publish Tauri app
        uses: tauri-apps/tauri-action@v0
        id: tauri-build # Add an ID to reference outputs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        with:
          tagName: v__VERSION__
          releaseName: "RepoSnap v__VERSION__ (Linux)"
          releaseBody: "Linux build (AppImage)."
          releaseDraft: ${{ github.event.inputs.deploy == false }}
          args: "--bundles appimage --verbose"

      - name: Get Package Version
        uses: ./.github/actions/get-version-from-package
        id: package-version

      - name: Clean Up Unneeded Build Artifacts
        run: |
          rm -rf src-tauri/target/release/bundle/appimage/RepoSnap.AppDir
          ls -la src-tauri/target/release/bundle/appimage/

      - name: Upload to R2
        if: ${{ github.event.inputs.deploy == true }}
        uses: ./.github/actions/upload-to-r2
        id: r2-upload
        with:
          source-dir: src-tauri/target/release/bundle/appimage
          version: ${{ steps.package-version.outputs.version }}

      - name: Debug R2 Upload Outputs
        if: ${{ github.event.inputs.deploy == 'true' }}
        run: |
          echo "Upload Result: ${{ steps.r2-upload.outputs.result }}"
          echo "Uploaded File URLs: ${{ steps.r2-upload.outputs.file-urls }}"
