name: Build Tauri App (Linux)

on:
  workflow_dispatch:

jobs:
  build-linux:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash -s -- "bun-v1.1.13"
      - name: Add Bun to PATH
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Install frontend dependencies
        run: bun install
      - name: Build and publish Tauri app
        uses: tauri-apps/tauri-action@v0
        id: tauri-build # Add an ID to reference outputs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        with:
          tagName: v__VERSION__
          releaseName: "RepoSnap v__VERSION__ (Linux)"
          releaseBody: "Linux build (AppImage)."
          releaseDraft: true
          args: "--bundles appimage --verbose"

      # Configure AWS Credentials for S3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # e.g., us-east-1
          # For S3-compatible storage other than AWS, add endpoint-url
          endpoint-url: ${{ secrets.S3_ENDPOINT_URL }} # e.g., https://your-s3-compatible-endpoint

      # Upload artifacts to Cloudflare R2
      - name: Upload to R2
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: src-tauri/target/release/bundle/appimage
          destination-dir: releases/v0.1.0
          output-file-url: true
