name: Build Tauri App (All Platforms - Single Release)

on:
  workflow_dispatch:

jobs:
  build-and-release:
    permissions:
      contents: write # Needed to create releases
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            target: aarch64-apple-darwin
            args: "--target aarch64-apple-darwin --bundles dmg"
          - platform: macos-latest
            target: x86_64-apple-darwin
            args: "--target x86_64-apple-darwin --bundles dmg"
          - platform: ubuntu-22.04
            target: x86_64-unknown-linux-gnu # Optional target specifier for clarity
            args: "--bundles appimage"
          - platform: windows-latest
            target: x86_64-pc-windows-msvc # Optional target specifier for clarity
            args: "--bundles msi"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      # Bun Setup (Conditional for different OS shells)
      - name: Install Bun (Unix)
        if: runner.os != 'Windows'
        run: curl -fsSL https://bun.sh/install | bash -s -- "bun-v1.1.13"
      - name: Add Bun to PATH (Unix)
        if: runner.os != 'Windows'
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH
      - name: Install Bun (Windows)
        if: runner.os == 'Windows'
        run: powershell -Command "irm bun.sh/install.ps1 | iex"
      - name: Add Bun to PATH (Windows)
        if: runner.os == 'Windows'
        run: echo "$env:USERPROFILE\.bun\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Install necessary targets only on macOS runners
          targets: ${{ matrix.platform == 'macos-latest' && format('{0},{1}', matrix.target, 'aarch64-apple-darwin,x86_64-apple-darwin') || matrix.target }}

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: bun install

      # Build and release using tauri-action
      - uses: tauri-apps/tauri-action@v0
        id: tauri-build # Add an ID to reference outputs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }} # Pass the signing key
          # Optional: TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: . # Optional: Explicitly set project path if not root
          tagName: v__VERSION__ # Use placeholder for automatic version fetching
          releaseName: "RepoSnap v__VERSION__"
          releaseBody: "Draft release for v__VERSION__."
          releaseDraft: true # Create a draft release
          prerelease: false
          # includeUpdaterJson: true # This is true by default when tagName is set
          args: ${{ matrix.args }} --verbose # Pass matrix args (target, bundles) and keep verbose
          # Optional: Specify tauriScript if bun isn't detected automatically
          # tauriScript: bun tauri
      # Configure AWS Credentials for S3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # e.g., us-east-1
          # For S3-compatible storage other than AWS, add endpoint-url
          endpoint-url: ${{ secrets.S3_ENDPOINT_URL }} # e.g., https://your-s3-compatible-endpoint

      # Upload to S3-compatible bucket
      - name: Upload to S3
        run: |
          aws s3 cp ./target/release/bundle/ s3://reposnap/${{ matrix.target }}/ --recursive --exclude "*" --include "*.dmg" --include "*.appimage" --include "*.msi"
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          # For non-AWS S3-compatible storage, uncomment and set endpoint
          AWS_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
