name: Build Tauri App (Windows)

on:
  push:
    branches:
      - release
  workflow_dispatch: # Manual trigger

jobs:
  build-windows:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install frontend dependencies
        run: npm install
      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "My App v__VERSION__ (Windows)"
          releaseBody: "Unsigned Windows build (.msi)."
          releaseDraft: true
          args: "--bundles msi"
