name: Build Tauri App (Windows)

on:
  workflow_dispatch:

jobs:
  build-windows:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Bun
        run: powershell -Command "irm bun.sh/install.ps1 | iex"
      - name: Add Bun to PATH
        run: echo "$env:USERPROFILE\.bun\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install frontend dependencies
        run: bun install
      - name: Build and publish Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        with:
          tagName: v__VERSION__
          releaseName: "RepoSnap v__VERSION__ (Windows)"
          releaseBody: "Windows build (.msi)."
          releaseDraft: true
          args: "--bundles msi --verbose"

      - name: Debug Tauri Outputs
        run: |
          echo "Tauri version output: ${{ steps.tauri-build.outputs.version }}"
          echo "Release ID: ${{ steps.tauri-build.outputs.releaseId }}"
          if [ -z "${{ steps.tauri-build.outputs.version }}" ]; then
            VERSION=$(jq -r '.version' src-tauri/tauri.conf.json)
            echo "Fallback version from tauri.conf.json: $VERSION"
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "VERSION=${{ steps.tauri-build.outputs.version }}" >> $GITHUB_ENV
          fi

      - name: Upload Windows MSI to R2
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: src-tauri/target/release/bundle/msi
          destination-dir: releases/${{ env.VERSION }}
          output-file-url: true
