name: Build Tauri App (Windows)

on:
  workflow_dispatch:

jobs:
  build-windows:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Bun
        run: powershell -Command "irm bun.sh/install.ps1 | iex"
      - name: Add Bun to PATH
        run: echo "$env:USERPROFILE\.bun\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install frontend dependencies
        run: bun install
      - name: Build and publish Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        with:
          tagName: v__VERSION__
          releaseName: "RepoSnap v__VERSION__ (Windows)"
          releaseBody: "Windows build (.msi)."
          releaseDraft: true
          args: "--bundles msi --verbose"
