name: Build Tauri App (Linux)

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: "Deploy to R2"
        required: false
        type: boolean
        default: false

jobs:
  build-linux:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: bun install

      - name: Build and publish Tauri app
        uses: tauri-apps/tauri-action@v0
        id: tauri-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        with:
          tagName: v__VERSION__
          releaseName: "RepoSnap v__VERSION__ (Linux)"
          releaseBody: "Linux build (AppImage)."
          releaseDraft: true
          args: "--bundles appimage --verbose"

      - name: Get Package Version
        uses: ./.github/actions/get-version-from-package
        id: package-version

      - name: Clean Up Unneeded Build Artifacts
        run: |
          rm -rf src-tauri/target/release/bundle/appimage/RepoSnap.AppDir
          ls -la src-tauri/target/release/bundle/appimage/

      - name: Debug Deploy Condition
        if: ${{ github.event.inputs.deploy == 'true' }}
        run: |
          echo "Deploy input is: ${{ github.event.inputs.deploy }}"

      - name: Upload to R2 (AppImage)
        if: ${{ github.event.inputs.deploy == 'true' }}
        uses: ryand56/r2-upload-action@latest
        id: r2-upload
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: src-tauri/target/release/bundle/appimage
          destination-dir: releases/${{ steps.package-version.outputs.version }}
          output-file-url: true

      - name: Debug R2 Upload Outputs
        if: ${{ github.event.inputs.deploy == 'true' }}
        run: |
          echo "Upload Result: ${{ steps.r2-upload.outputs.result }}"
          echo "Uploaded File URLs: ${{ steps.r2-upload.outputs.file-urls }}"
